---
#Config Map for JavaService   
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: itg-gke-sbt-app-configmap
  namespace: default
data:
  application.yml: |
    spring:
      profile: 
        active: blue
    common:
      property1: value1
      property2: value2
      property3: value3
      
---

---
# SpringBoot itg-gke-sbt-app deployment
---    
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: itg-gke-sbt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itg-gke-sbt-app
  template:
    metadata:
      labels:
        app: itg-gke-sbt-app
    spec:
      containers:
        - name: itg-gke-sbt-app
          image: asia-south1-docker.pkg.dev/sigma-zodiac-400712/itg-docker-repo/itg-gke-sbt-app:latest
          ports:
          - containerPort: 8899         
          volumeMounts:
          - name: itg-config-volume
            mountPath: /config
      volumes:
        - name: itg-config-volume
          configMap:
            name: itg-gke-sbt-app-configmap

---
# SpringBoot itg-gke-sbt-app service
---        

apiVersion: v1
kind: Service
metadata:
  name: itg-gke-sbt-app
  namespace: default
spec:
  selector:
    app: itg-gke-sbt-app
  ports:
    - port: 8899
      targetPort: 8899


---
# Ingress Controller config for GKE
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: path-testing-ingress-v2
  annotations:
    kubernetes.io/ingress.global-static-ip-name: lb-ingress-v2
    nginx.ingress.kubernetes.io/proxy-set-headers: "Host $host, X-Real-IP $remote_addr"
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/access-log-path: "/var/log/nginx/access.log"
    nginx.ingress.kubernetes.io/log-format-upstream: "json"
    nginx.ingress.kubernetes.io/log-format: "json"    
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2    
  labels:
    app: path-testing-ingress
spec:
#  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: itg-gke-sbt-app
                port:
                  number: 8899
          - path: /app/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: itg-gke-sbt-app
                port:
                  number: 8899
          - path: /routes/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: itg-gke-sbt-app
                port:
                  number: 8899
          - path: /myapp
            pathType: ImplementationSpecific
            backend:
              service:
                name: itg-gke-sbt-app
                port:
                  number: 8899          
          - path: /sbtapp/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: itg-gke-sbt-app
                port:
                  number: 8899
                  