
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log info;
pid        /var/run/nginx.pid;

load_module modules/ngx_http_js_module.so;

events {
    worker_connections  1024;
}
 
http {

     log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    js_path "/etc/nginx/njs/";

    js_import github_oidc from oidc/gitlab_oidc.js;
   # js_set $oidc_redirect github_oidc.redirect;
    js_set $oidc_callback github_oidc.callback;
    js_set $oidc_auth_request github_oidc.auth_request;
    js_set $oidc_validate github_oidc.validate;
	js_set $oidc_auth_url github_oidc.get_auth_url;
	js_set $oidc_session_tkn github_oidc.auth_request;

    js_import utils.js;
    js_import main from http/hello.js;
    js_import genjwt from http/authorization/gen_hs_jwt.js;
    js_set $jwt genjwt.jwt;
	
	map $cookie_session_token $session_token {
			default "";
			"~*session_token=([^;]+)" $1;
		}

    server {
        listen 8080;
  	root /usr/share/nginx/html;

	 location /ui {
	    rewrite ^/ui(.*)$ $1 break;
	    try_files $uri $uri/ /index.html;
	  }

	  error_page   500 502 503 504  /50x.html;

	  location = /50x.html {
	    root   /usr/share/nginx/html;
	  }
	 

	  location = /version {
	    js_content utils.version;
	  }
	  
	  location = /hello {
	    js_content main.hello;
	  }

	  location /jwt {
	    return 200 $jwt;
	  }

        location /login {
            return 301 $oidc_auth_url;
        }

	 location /loginv3 {
	    return 301 https://gitlab.com/oauth/authorize?client_id=hhhhhhhhhhhh&response_type=code&redirect_uri=http://192.168.1.14:8080/callback&scope=openid&state=asdasdprakash;
	  }


        location /callback {
            js_content github_oidc.callback;
        }

		location /oauth/discovery/keys {
			proxy_ssl_protocols TLSv1.2 TLSv1.3;
			resolver 8.8.8.8 ipv6=off;
            proxy_pass https://gitlab.com;
			proxy_set_header User-Agent nginx-njs;
        }

        location /internal/token {
			internal;
            proxy_pass http://192.168.1.17:3001/mocks/oauth/token;
			proxy_ssl_protocols TLSv1.2 TLSv1.3;
			proxy_ssl_verify off;  # Use with caution
			resolver 8.8.8.8 ipv6=off;
        }

        location /internal/userinfo {
			internal;
            proxy_pass https://gitlab.com/oauth/userinfo;
            proxy_set_header Host api.github.com;
            proxy_set_header Authorization $http_authorization;
            proxy_set_header User-Agent nginx-njs;
        }
		
		

        location /apis {
			proxy_set_header X-User-Token $oidc_session_tkn;
			proxy_set_header X-User-Token-prak "asdasd";
            proxy_pass http://192.168.1.17:3001;
			#js_content github_oidc.auth_request;
            proxy_set_header X-User-Id $http_x_user_id;
            proxy_set_header X-User-Email $http_x_user_email;
            proxy_set_header X-User-Name $http_x_user_name;
        }
    }
}
